spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    schema: classpath:/schema.sql
    data: classpath:/import.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true