eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
zuul:
  prefix: /service
  sensitive-headers:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000