eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
spring:
  datasource:
    url: ${TECHNOLOGY_DS_URL:jdbc:mysql://localhost:3306/technology?useSSL=false}
    username: ${TECHNOLOGY_DS_USERID:root}
    password: ${TECHNOLOGY_DS_PASSWORD:rootpassword}
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/import.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
