eureka:
  client:
    service-url:
      defaultZone: {EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
